baseURL: "https://fakecore.me/"
title: fakecore
paginate: 8
theme: PaperModX

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
  env: fakecore blog # to enable google analytics, opengraph, twitter-cards and schema.
  description:
  author:
    - fakecore
  mainSections:
    - docs
    - posts
  disableAnchoredHeadings: true
  images: ["cover.png"]
  DateFormat: "2006-01-02"
  useCustomAnalytics: false

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  ShowWordCount: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true
  TocSide: "right"
  EnableInstantClick: true
  EnableImageZoom: true
  comments: true
  profileMode:
    enabled: false
    title: fc
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: /archives/
      - name: Tags
        url: /tags/

  homeInfoParams:
    Title: "fakecore"
    Content: |
      Welcome to my blog.

      It's for life logger and tech-share.

  socialIcons:
    - name: github-simple
      url: "https://github.com/fakecore"
    # - name: rss-simple
    #   url: "index.xml"

  editPost:
    URL: "https://github.com/fakecore/fakecore.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        # - name: Docs
        #   url: /docs/
        #   weight: 1
        # - name: Newsletter
        #   url: /newsletter/
        #   weight: 1
        - name: Tags
          url: /tags/
          weight: 4
        - name: Archive
          url: /archives/
          weight: 5
        - name: Search
          url: /search/
          weight: 10
        - name: "aboutme"
          url: "aboutme/"

  zh:
    languageName: ":cn:"
    languageAltTitle: 中文
    weight: 2
    title: fakecore
    profileMode:
      enabled: true
      title: fakecore
      subtitle:
      buttons:
        # - name: 文档
        #   url: docs
        - name: 标签
          url: tags
    menu:
      main:
        # - name: 文档
        #   url: docs
        #   weight: 1
        - name: 标签
          url: tags/
          weight: 4
        - name: 归档
          url: archives
          weight: 5
        - name: 搜索
          url: search/
          weight: 10
        - name: "关于我"
          url: aboutme/

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
